### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by swei1125** [swei1125/Yeep#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] When errors are displayed, the input boxes should not move
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
  - [x] Errors should display for both `/signup` and`/login`.
  - [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Adequate and appropriate seeds
  - [x] Demo Login Works

**Comment by swei1125** [comment]
I will style the logo later : )

**Comment by xnanodax** [comment]
Great work!!

> Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
Watch out for this requirement!

---- 
- [x] I would take off the list-style on the li of the errors
![screen shot 2018-08-08 at 9 47 32 pm](https://user-images.githubusercontent.com/20424731/43878572-b631c2d0-9b54-11e8-835e-0b5ef03403df.png)

----

- [x] Consider adding more space between the input fields:
Yelp's
![screen shot 2018-08-08 at 9 45 32 pm](https://user-images.githubusercontent.com/20424731/43878579-c782310a-9b54-11e8-9116-bf7840322414.png)

Yeep's:
![screen shot 2018-08-08 at 9 45 37 pm](https://user-images.githubusercontent.com/20424731/43878580-c8fbb394-9b54-11e8-872f-20c5d156d502.png)

**Comment by swei1125** [comment]
Fixed the sign up form, errors style, and random url issue

**Comment by xnanodax** [comment]
Looks good!
