### ISSUE TITLE
PA Review: Business Page

### ISSUE THREAD

**Issue by swei1125** [swei1125/Yeep#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x]  Presentational Components
- [x] Styling
- [x] Smooth, bug free navigation
- [x]  Adequate and appropriate seeds

**Comment by swei1125** [comment]
For now I only have 2 bizs in my database, so just type out the path `bizs/1` or `bizs/2` to look at the biz show page :)

**Comment by swei1125** [comment]
also, I add the "add photo" functionality.

**Comment by xnanodax** [comment]
Consider the spacing between the address fields of show page!
![screen shot 2018-08-15 at 10 00 44 am](https://user-images.githubusercontent.com/20424731/44161428-29a20500-a072-11e8-933a-356a9052ddc9.png)
![screen shot 2018-08-15 at 10 01 04 am](https://user-images.githubusercontent.com/20424731/44161431-2c045f00-a072-11e8-90d7-1030a0d379f2.png)

**Comment by swei1125** [comment]
fixed the address line spacing

**Comment by xnanodax** [comment]
Looks great!
