### ISSUE TITLE
PA Review: Search and Bizs Index Page

### ISSUE THREAD

**Issue by swei1125** [swei1125/Yeep#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling 
- [x] Smooth, bug free navigation
- [x]  Adequate and appropriate seeds

**Comment by xnanodax** [comment]
- [ ] Consider the text alignment of the place holders with the labels of the inputs!
![screen shot 2018-08-15 at 9 57 52 am 1](https://user-images.githubusercontent.com/20424731/44161335-df208880-a071-11e8-87fb-41187d62f45b.png)

**Comment by swei1125** [comment]
That's weird. The site on my computer doesn't look like this, mine's like the all the text in the center, also my 'Hi Guest' in my browser stay in one line.
<img width="976" alt="screen shot 2018-08-15 at 10 10 17 am" src="https://user-images.githubusercontent.com/38794088/44161882-79cd9700-a073-11e8-9d26-7a03a8846675.png">
